version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  asynqmon:
    image: hibiken/asynqmon
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=redis:6379
  triton:
    # image: nvcr.io/nvidia/tritonserver:23.05-py3
    build:
      context: docker
      dockerfile: triton.Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - ./model_repository:/models
    command: ["tritonserver",  "--model-repository=/models"]
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]